export const TOPICS = {
  en: [
    "Books",
    "Coins",
    "Stamps",
    "Postcards",
    "Comics",
    "Action Figures",
    "Trading Cards",
    "Vinyl Records",
    "Movie Memorabilia",
    "Sports Jerseys",
    "Autographs",
    "Art Prints",
    "Antique Furniture",
    "Vintage Clothing",
    "Toy Cars",
    "Dolls",
    "Model Trains",
    "Musical Instruments",
    "Movie Props",
    "Fine China",
    "Wristwatches",
    "Jewelry",
    "Comic Books",
    "Bottles",
    "Sports Memorabilia",
    "Board Games",
    "Vintage Cameras",
    "Sneakers",
    "Figurines",
    "Vinyl Toys",
    "Vintage Posters",
    "Concert Tickets",
    "Vintage Magazines",
    "Musical Records",
    "Action Cameras",
    "Snow Globes",
    "Candles",
    "Shot Glasses",
    "Beer Steins",
    "Vintage Maps",
    "Pocket Knives",
    "Trading Pins",
    "Artifacts",
    "Antique Clocks",
    "Hats",
    "Lighters",
    "Fountain Pens",
    "Vintage Telephones",
    "Vinyl Music Albums",
    "Other",
  ] as const,

  ru: [
    "Книги",
    "Монеты",
    "Марки",
    "Открытки",
    "Комиксы",
    "Action Figures",
    "Торговые карты",
    "Виниловые пластинки",
    "Мемориальные вещи",
    "Спортивные футболки",
    "Автографы",
    "Художественные принты",
    "Антикварная мебель",
    "Винтажная одежда",
    "Игрушечные автомобили",
    "Куклы",
    "Модели поездов",
    "Музыкальные инструменты",
    "Реквизит для кино",
    "Изящный фарфор",
    "Наручные часы",
    "Ювелирные изделия",
    "Комиксы",
    "Бутылки",
    "Спортивные сувениры",
    "Настольные игры",
    "Старинные фотоаппараты",
    "Кроссовки",
    "Фигурки",
    "Виниловые игрушки",
    "Винтажные плакаты",
    "Концертные билеты",
    "Винтажные журналы",
    "Музыкальные пластинки",
    "Экшн-камеры",
    "Снежные глобусы",
    "Свечи",
    "Рюмки",
    "Пивные стаканы",
    "Старинные карты",
    "Карманные ножи",
    "Торговые значки",
    "Артефакты",
    "Антикварные часы",
    "Шляпы",
    "Зажигалки",
    "Перьевые ручки",
    "Старинные телефоны",
    "Виниловые музыкальные альбомы",
    "Прочее",
  ] as const,
};
